import { PhoneDirectory } from "../models/PhoneDirectory";

const phoneData = [
  { number: "0", name: "SANTRAL (BURCU DAĞDEVİREN)", department: "SANTRAL" },
  { number: "100", name: "SANTRAL (SEKRETERLİK)", department: "SANTRAL" },
  { number: "101", name: "SEVİL ÖNDER (Masa)", department: "YÖNETİM ASİSTANI" },
  { number: "103", name: "A KAPISI (İdari Bina)", department: "GÜVENLİK" },
  { number: "104", name: "A KAPISI (İdari Bina)", department: "GÜVENLİK" },
  { number: "105", name: "ZEKİ KIRŞAN (mobil)", department: "MAKİNE" },
  { number: "106", name: "B KAPISI (Personel Güvenlik)", department: "GÜVENLİK" },
  { number: "107", name: "BERKAN BEYAZ (mobil)", department: "SATIN ALMA" },
  { number: "109", name: "DIŞ KAPI (Doğan Gülşen)", department: "GÜVENLİK" },
  { number: "110", name: "DIŞ KAPI (Nevzat Kurt)", department: "GÜVENLİK" },
  { number: "111", name: "HALUK ZIRH (mobil)", department: "İDARİ İŞLER" },
  { number: "112", name: "HALUK ZIRH (Odası)", department: "İDARİ İŞLER" },
  { number: "113", name: "GARAJ (mobil)", department: "GARAJ" },
  { number: "114", name: "GARAJ", department: "GARAJ" },
  { number: "115", name: "DİLEK ARDABOYU", department: "PERSONEL" },
  { number: "115", name: "İLAYDA ASLANER", department: "PERSONEL" },
  { number: "117", name: "İLHAN ERDEMLİ (mobil)", department: "FİNANS" },
  { number: "118", name: "SEVİL ÖNDER (mobil)", department: "YÖNETİM ASİSTANI" },
  { number: "120", name: "ŞENAY ÜRERSOY (mobil)", department: "TASARIM NUMUNE" },
  { number: "122", name: "BAKIM ONARIM", department: "BAKIM ONARIM" },
  { number: "123", name: "PERİHAN ÜNAL (mobil)", department: "PLANLAMA" },
  { number: "124", name: "FERHAT KARADENİZ (mobil)", department: "SEVKİYAT" },
  { number: "125", name: "ŞEMEN HANIM (mobil)", department: "YÖNETİM" },
  { number: "126", name: "ATÖLYE", department: "ÜRETİM" },
  { number: "129", name: "KEREM KAYA (mobil)", department: "İDARİ İŞLER" },
  { number: "130", name: "MURAT ÖZBARDAKÇI (mobil)", department: "FASON" },
  { number: "131", name: "BÜLENT BEY", department: "YÖNETİM" },
  { number: "136", name: "NESLİHAN ONKARDEŞ", department: "MUHASEBE" },
  { number: "138", name: "TURHAN ASLANER (Odası)", department: "MUHASEBE" },
  { number: "139", name: "MALİ MÜŞAVİRLER", department: "MUHASEBE" },
  { number: "142", name: "LEYLA AYDOĞDU", department: "MUHASEBE" },
  { number: "143", name: "BERLİN SÜMER", department: "MUHASEBE" },
  { number: "146", name: "EMİRHAN AKKAYA (mobil)", department: "KALİPHANE" },
  { number: "149", name: "ÖZCAN EFE (mobil)", department: "BİLGİ İŞLEM" },
  { number: "150", name: "MELEK UĞUŞ (mobil)", department: "ÇAY OCAĞI" },
  { number: "153", name: "BAŞAK KAVAK (mobil)", department: "KALİPHANE" },
  { number: "154", name: "PAKETLEME (mobil)", department: "PAKETLEME" },
  { number: "155", name: "BANU EKŞİ", department: "İHRACAT PAZ." },
  { number: "157", name: "PAKETLEME", department: "PAKETLEME" },
  { number: "158", name: "BARIŞ GENÇ (mobil)", department: "İNSAN KAYNAKLARI + İSG" },
  { number: "159", name: "EFECAN DUMAN", department: "İHRACAT PAZ." },
  { number: "160", name: "KUDRET YALÇIN TEKİN (mobil)", department: "İNSAN KAYNAKLARI + İSG" },
  { number: "161", name: "BURAK KILIÇ", department: "İHRACAT PAZ." },
  { number: "163", name: "LİNE ODASI", department: "İHRACAT PAZ." },
  { number: "168", name: "KURUTRAŞ", department: "TRAŞ BÖLÜMÜ FASON" },
  { number: "170", name: "ZİNCİR ÖRME", department: "MAKİNE" },
  { number: "171", name: "BURAK KARTAL (mobil)", department: "KALİPHANE" },
  { number: "172", name: "HARUN YİĞİT (mobil)", department: "MAKİNE" },
  { number: "173", name: "ÖZCAN NİŞAN (mobil)", department: "TASARIM NUMUNE" },
  { number: "175", name: "MUHAMMED ALTINTAŞ (mobil)", department: "MONTAJ" },
  { number: "176", name: "GÜVENLİK SERDAR YILMAZ", department: "GÜVENLİK" },
  { number: "178", name: "ZÜLEYHA ÖZTÜRK", department: "MUHASEBE" },
  { number: "182", name: "EĞİTİM ODASI 1.KAT", department: "TOPLANTI ODALARI" },
  { number: "185", name: "FİNANS", department: "FİNANS" },
  { number: "187", name: "ASTAR ÇEKME", department: "ÜRETİM" },
  { number: "188", name: "ASANSÖR", department: "ASANSÖR" },
  { number: "189", name: "YILMAZ GÜMÜŞ (mobil)", department: "MONTAJ" },
  { number: "190", name: "KAYNAK", department: "İÇİBOŞ" },
  { number: "191", name: "ASİT", department: "LABORATUAR + ANALİZ LAB." },
  { number: "192", name: "BURAK ÖNDER OCAK (mobil)", department: "ÜRETİM" },
  { number: "193", name: "B KAPISI (Personel Güvenlik) mobil", department: "GÜVENLİK" },
  { number: "194", name: "BAR Bölümü", department: "MAKİNE" },
  { number: "195", name: "LABORATUAR + ANALİZ LAB.", department: "LABORATUAR + ANALİZ LAB." },
  { number: "196", name: "HALUK YAKIN (mobil)", department: "MONTAJ" },
  { number: "198", name: "MUSTAFA UĞUR (mobil)", department: "SATIN ALMA" },
  { number: "200", name: "ARİFE ÖZDEMİR", department: "ÇAY OCAĞI" },
  { number: "203", name: "FURKAN ÖZTEKİN (mobil)", department: "BİLGİ İŞLEM" },
  { number: "204", name: "ERKAN MUSTAFA ÇAKIR (mobil)", department: "BİLGİ İŞLEM" },
  { number: "205", "name": "ÖZLEM KÖKER (mobil)", "department": "MONTAJ" },
  { number: "206", name: "TURHAN ASLANER (mobil)", department: "MUHASEBE" },
  { number: "227", name: "OSMAN ÖZTEKİN (127 mobil)", department: "SEVKİYAT" },
  { number: "229", name: "MAKİNE MERKEZ", department: "MAKİNE" },
  { number: "230", name: "ŞEMEN HANIM Odası", department: "YÖNETİM" },
  { number: "231", name: "KÜP", department: "MAKİNE" },
  { number: "232", name: "BUZLAMA 323", department: "TRAŞ BÖLÜMÜ-FASON" },
  { number: "233", name: "MAKİNE", department: "İÇİBOŞ" },
  { number: "234", name: "MEHMET ÖZTEKİN (mobil)", department: "MAKİNE" },
  { number: "235", name: "BİSMARK", department: "MAKİNE" },
  { number: "236", name: "ÇEKİÇLEME", department: "MAKİNE" },
  { number: "237", name: "KAYNAK", department: "MAKİNE" },
  { number: "238", name: "TEMİZLEME", department: "MAKİNE" },
  { number: "239", name: "UĞUR ATMACA (mobil)", department: "KALİPHANE" },
  { number: "241", name: "SAİT BUDAK", department: "ÜRETİM" },
  { number: "242", name: "SEVAN ÖZÇERKES (mobil)", department: "ÜRETİM" },
  { number: "243", name: "SEMİR UMUÇ (mobil)", department: "ÜRETİM" },
  { number: "245", name: "ATÖLYE BAR", department: "ÜRETİM" },
  { number: "246", name: "DÖKÜM", department: "ÜRETİM" },
  { number: "247", name: "HASAN HÜSEYİN ÇAĞLAR (mobil)", department: "BİLGİ İŞLEM" },
  { number: "248", name: "PRESHANE", department: "ÜRETİM" },
  { number: "249", name: "MEKANİK", department: "ÜRETİM" },
  { number: "250", name: "TAŞLAMA", department: "ÜRETİM" },
  { number: "251", name: "OCAK HADDE", department: "ÜRETİM" },
  { number: "252", name: "ERİTME", department: "ÜRETİM" },
  { number: "253", name: "KUTLUHAN ALBAŞ (mobil)", department: "TEKNİK ARGE" },
  { number: "254", name: "OCAK TEL VE ASTAR ÇEKME", department: "ÜRETİM" },
  { number: "255", name: "BAHAR ALTINTOPRAK (mobil)", department: "MONTAJ" },
  { number: "256", name: "ARMAN YESAYAN (mobil)", department: "FASON" },
  { number: "257", name: "DEPO", department: "DEPO" },
  { number: "258", name: "AYDIN ERKEK (mobil)", department: "MONTAJ" },
  { number: "259", name: "LAZER (GÖKTÜRK GÖKKAYA)", department: "MONTAJ" },
  { number: "260", name: "FANTAZİ / LAZER KAYNAK", department: "MONTAJ" },
  { number: "261", name: "FANTAZİ-VEDAT TEZGAH", department: "MONTAJ" },
  { number: "262", name: "CİLA", department: "MONTAJ" },
  { number: "263", name: "YALDIZ", department: "MONTAJ" },
  { number: "264", name: "METİN GÜZEL (mobil)", department: "LABORATUAR + ANALİZ LAB." },
  { number: "265", name: "GİZEM KAYATÜRK (mobil)", department: "PLANLAMA" },
  { number: "266", name: "KALİTE KONTROL", department: "KALİTE KONTROL" },
  { number: "267", name: "ÖZCAN ULA (mobil) Sağlık Memur", department: "DOKTOR" },
  { number: "267", name: "Dr. TARIK TURFAN", department: "DOKTOR" },
  { number: "268", name: "ELEKTRONİK", department: "ELEKTRİK" },
  { number: "270", name: "YEMEKHANE", department: "SOFRA ECEM 177" },
  { number: "271", name: "LAZER", department: "MONTAJ" },
  { number: "272", name: "ELEKTRİK ODASI (Faruk Ali Çelen)", department: "ELEKTRİK" },
  { number: "274", name: "KADİR ÖZDEMİR (mobil)", department: "KALİPHANE" },
  { number: "275", name: "KALİPHANE", department: "KALİPHANE" },
  { number: "276", name: "ÇAĞLA ALTUNEL", department: "İHRACAT PAZ." },
  { number: "277", name: "KERİM YEŞİLYURT (mobil)", department: "GRAFİK" },
  { number: "278", name: "ENGİN ÇAĞLAR (mobil)", department: "FASON" },
  { number: "279", name: "MURAT MAĞZALCIOĞLU (mobil)", department: "TİCARİ PAZARLAMA" },
  { number: "280", name: "KUBİLAY AKKIZ (mobil)", department: "BİLGİ İŞLEM" },
  { number: "282", name: "KADİR İLHAN", department: "İHRACAT PAZ." },
  { number: "283", name: "ARA MADEN (mobil)", department: "ÜRETİM" },
  { number: "284", name: "SEDAT KARAMANLI (mobil)", department: "TEKNİK ARGE" },
  { number: "303", name: "SANTRAL (BURCU HN.) mobil", department: "SANTRAL" },
  { number: "304", name: "MİNE", department: "MONTAJ" },
  { number: "305", name: "BURAK KÜSDÜL", department: "İHRACAT PAZ." },
  { number: "306", name: "EMİRHAN TÖNEL (mobil)", department: "MKP" },
  { number: "310", name: "HAKAN BEY (mobil)", department: "YÖNETİM" },
  { number: "312", name: "MONTAJ KESME (TRAŞ KONTROL)", department: "MONTAJ" },
  { number: "313", name: "GİRİŞ KAT (MİDAS PAZ.)", department: "TOPLANTI ODALARI" },
  { number: "315", name: "CEYDA ÜNÜVAR", department: "İHRACAT PAZ." },
  { number: "319", name: "GAMZE GÜZEL (mobil)", department: "ÜRETİM" },
  { number: "321", name: "MESUT SATIŞ (mobil)", department: "MKP" },
  { number: "322", name: "GİZEM ÇINAR (mobil)", department: "İNSAN KAYNAKLARI + İSG" },
  { number: "325", name: "ÖMER ÖZTEKİN - MURAT ORUÇOĞLU", department: "BAKIM ONARIM" },
  { number: "326", name: "RIDVAN ASLAN (mobil)", department: "MAKİNE" },
  { number: "328", name: "GİZEM ORHAN", department: "İHRACAT PAZ." },
  { number: "329", name: "GÖKHAN BEY Odası", department: "YÖNETİM" },
  { number: "330", name: "GÖKHAN BEY (mobil)", department: "YÖNETİM" },
  { number: "332", name: "DİLARA EĞRİ SEDEF KARA", department: "GRAFİK" },
  { number: "336", name: "VEYSEL ARSLAN Met. (mobil) - TEKNİK ARGE", department: "TEKNİK ARGE" },
  { number: "337", name: "TUGAY ORAK Met. (mobil) - TEKNİK ARGE", department: "TEKNİK ARGE" },
  { number: "339", name: "DOĞUKAN ASLAN (mobil)", department: "MONTAJ" },
  { number: "340", name: "BAKIM (mobil)", department: "BAKIM ONARIM" },
  { number: "341", name: "DÖKÜM", department: "MONTAJ" },
  { number: "342", name: "SERKAN KRANDA (mobil)", department: "LABORATUAR + ANALİZ LAB." },
  { number: "343", name: "ELVİN HN - SEÇİL HN", department: "TASARIM NUMUNE" },
  { number: "344", name: "DEVRİM NUR KARAMAN (mobil)", department: "LABORATUAR + ANALİZ LAB." },
  { number: "345", name: "BERAT KARAKOÇ Met. (mobil) - TEKNİK ARGE", department: "TEKNİK ARGE" },
  { number: "346", name: "ATÖLYE BAR mobil", department: "ÜRETİM" },
  { number: "347", name: "CAN HAMARAT (mobil)", department: "LABORATUAR + ANALİZ LAB." },
  { number: "348", name: "FURKAN ARDA AYDOĞAN (mobil)", department: "LABORATUAR + ANALİZ LAB." },
  { number: "349", name: "YÖNETİM KATI 2.KAT", department: "TOPLANTI ODALARI" },
  { number: "350", name: "LAZER KAYNAK", department: "MONTAJ" },
];

export const seedPhoneDirectory = async () => {
  try {
    // Clear existing data (optional, but good for refresh)
    await PhoneDirectory.destroy({ where: {}, truncate: false }); // Truncate might fail due to FK, but there are no FKs yet.
    
    // Bulk create
    await PhoneDirectory.bulkCreate(phoneData);
    console.log("Phone directory seeded successfully!");
  } catch (error) {
    console.error("Error seeding phone directory:", error);
  }
};
